services:
  postgres_weather:
    image: postgres:13
    container_name: postgres_weather_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: weather
    ports:
      - "5433:5432"
    volumes:
      - postgres_weather_data:/var/lib/postgresql/data
    networks:
      - airflow

volumes:
  postgres_weather_data:

networks:
  airflow: {}